FROM golang AS build
RUN curl https://glide.sh/get | sh
WORKDIR /go/src/app
COPY ./glide.lock .
COPY ./glide.yaml .
RUN glide install
COPY . .
RUN go build -ldflags "-linkmode external -extldflags -static" server.go

FROM alpine AS production
COPY --from=build /go/src/app/server /root
RUN chmod +x /root/server
ENTRYPOINT /root/server
