type: {{serviceType}}
description: {{description}}
author: {{author}}

startup:
  online-text: online at port

messages:
  receives:
    - ping
  sends:
    - pong

dependencies:

development:
  scripts:
    run: go run server.go
    test: go test
