type: {{serviceType}}
description: {{description}}
author: {{author}}

startup:
  command: go run server.go
  online-text: online at port
tests: go test

messages:
  receives:
    - ping
  sends:
    - pong

dependencies:
